### ISSUE TITLE
getResponseElement Error

### ISSUE THREAD

**Issue by nacu4** [garethlatwork/quickbase_client#13]
I'm pretty new here so I'm very open to feedback / providing additional info. I'm in the very early stages of trying to get a ruby connection to Quickbase. I'm part of a large company with many applications. I'm the Admin for my App, but not for Quickbase as a whole. I'm trying to get the table ID's for my application so that I can query off of them (the DBID does not appear to work), but I get this error. 

![image](https://user-images.githubusercontent.com/22282824/45561265-31cd9b80-b7fc-11e8-947b-3d1828d23a5a.png)

This is my code:
`require 'QuickBaseClient'
qbc = QuickBase::Client.new(username = "[quickbase_user]", password = "[my password]", appname = "[My App Name]", useSSL = true, printRequestsAndResponses = false, stopOnError = false, showTrace = false, org = "tesla", apptoken = "[My App Token]", debugHTTPConnection = false, domain = "quickbase", proxy_options = nil)
puts "\nThe QuickBase Support Center has these child tables:\n\n"
puts QuickBase::Client.new.getTableIDs("[My App DBID]").join("\n")
`

Any advice?

**Comment by ShaunGrey** [comment]
i no longer have access to a quickbase app to test that out on, but if you run the exact same code but change "printRequestsAndResponses = false" to "printRequestsAndResponses = true", does it give you anymore info?

Basically, I'm wondering if the issue is with the connection to quickbase itself, or with the ruby API wrapper.

**Comment by nacu4** [comment]
I still get the error if I make that true. 

It appears as if the issue is with this phrase

`puts QuickBase::Client.new.getTableIDs("bmfp897u2").join("\n")`

If I get rid of this, everything goes well. The "bmfp" number that I'm using is from Quickbase as the Application DBID. Maybe that's not what should be put there?

**Comment by ShaunGrey** [comment]
Try:

`puts qbc.getTableIDs("bmfp897u2").join("\n")`

**Comment by nacu4** [comment]
I no longer get that error, thanks! That makes a lot of sense. 

This is now the error I get (And it repeats this a few times): 

The QuickBase Support Center has these child tables:


Request: -------------------------------------------
"https://tesla.quickbase.com:443/db/bmfp897u2"
{"Content-Type"=>"application/xml", "Content-Length"=>"29", "QUICKBASE-ACTION"=>"API_getSchema"}
"<qdbapi><usertoken/></qdbapi>"

Response: ------------------------------------------
"200"
"<?xml version=\"1.0\" ?>\r\n<qdbapi>\n\t<action>API_getSchema</action>\r\n\t<errcode>24</errcode>\r\n\t<errtext>Invalid Application Token</errtext>\r\n\t<errdetail>An Application Token must
 be supplied.</errdetail>\r\n</qdbapi>\r\n"


Request: -------------------------------------------
"https://tesla.quickbase.com:443/db/main"
{"Content-Type"=>"application/xml", "Content-Length"=>"29", "QUICKBASE-ACTION"=>"API_signOut"}
"<qdbapi><usertoken/></qdbapi>"

Response: ------------------------------------------
"200"
"<?xml version=\"1.0\" ?>\r\n<qdbapi>\n\t<action>API_signOut</action>\r\n\t<errcode>0</errcode>\r\n\t<errtext>No error</errtext>\r\n</qdbapi>\r\n"

**Comment by ShaunGrey** [comment]
The `qbc = QuickBase::Client.new` is what opens the connection to quickbase. Everything is predicated on that working correctly. Do you have reason to believe that your connection is actually being opened? If I recall correctly, quickbase_client was kinda bad at alerting you to a failed connection.

Make sure that printRequestsAndResponses is still set to "true" and then copy/paste all the output that you get from it here. I used to find that very helpful in debugging.

**Comment by nacu4** [comment]
OK printRequestsAndResponses is TRUE now. Below is what I get. I am looking through the `qbc = QuickBase::Client.new` statement now and am trying to debug... 

Request: -------------------------------------------
"https://tesla.quickbase.com:443/db/bmfp897u2"
{"Content-Type"=>"application/xml", "Content-Length"=>"29", "QUICKBASE-ACTION"=>"API_getSchema"}
""

Response: ------------------------------------------
"200"
"\r\n\n\tAPI_getSchema\r\n\t24\r\n\tInvalid Application Token\r\n\tAn Application Token must
be supplied.\r\n\r\n"

Request: -------------------------------------------
"https://tesla.quickbase.com:443/db/main"
{"Content-Type"=>"application/xml", "Content-Length"=>"29", "QUICKBASE-ACTION"=>"API_signOut"}
""

Response: ------------------------------------------
"200"
"\r\n\n\tAPI_signOut\r\n\t0\r\n\tNo error\r\n\r\n"

**Comment by ShaunGrey** [comment]
OK, I remember this: about a year ago someone came into this code and removed the ability to authenticate by username and password or apptoken. I don't know why they did it but you can see me complaining about it here and here:

https://github.com/garethlatwork/quickbase_client/issues/11
https://github.com/garethlatwork/quickbase_client/issues/12

You can see their changes, which made usertokens the only way to authenticate, here:
https://github.com/garethlatwork/quickbase_client/commit/46b1d75029d61d26325ad666b755a054d0b19d99

There are two fixes to this, so let's start with the simplest: see if you can follow the instructions here to get a usertoken for yourself: https://help.quickbase.com/api-guide/create_user_tokens.html

Then try replacing your initialization line with something like:
`qbc = QuickBase::Client.new(usertoken = "[Your Usertoken]", appname = [Your App Name], useSSL = true, printRequestsAndResponses = true, stopOnError = false, showTrace = false, org = "tesla", debugHTTPConnection = false, domain = "quickbase", proxy_options = nil)`

**Comment by nacu4** [comment]
Well that definitely changed the response! Here's what it returns: 

![image](https://user-images.githubusercontent.com/22282824/45568176-c93ce980-b810-11e8-9132-96114b191da8.png)

And, to refresh, here's my code: 
`require 'QuickBaseClient'
qbc = QuickBase::Client.new(usertoken = "[token]", appname = "[app_name]", useSSL = true, printRequestsAndResponses = true, stopOnError = false, showTrace = false, org = "[org]", apptoken = "[token]", debugHTTPConnection = false, domain = "quickbase", proxy_options = nil)
puts "\nThe QuickBase Support Center has these child tables:\n\n"
puts qbc.getTableIDs("bmfp897u2").join("\n")
`

**Comment by nacu4** [comment]
It appears as if it's trying to connect with the Quickbase Client via my Usertoken/Apptoken, but it's freezing or something. The code is cut off so I can't see everything. Maybe it is connecting successfully?

**Comment by ShaunGrey** [comment]
Let's simplify things by removing the last two lines so we're focusing on getting a successful connection. Change your code to this (and note that I've removed the `apptoken= "[token]"` parameter. You should no longer need it if you're authenticating via usertoken):

`require 'QuickBaseClient' `

`qbc = QuickBase::Client.new(usertoken = "[token]", appname = "[app_name]", useSSL = true, printRequestsAndResponses = true, stopOnError = false, showTrace = false, org = "[org]", debugHTTPConnection = false, domain = "quickbase", proxy_options = nil)' `

**Comment by nacu4** [comment]
![image](https://user-images.githubusercontent.com/22282824/45568635-00f86100-b812-11e8-9adb-49a7780fb253.png)

**Comment by nacu4** [comment]
I can copy/paste the text if that's easier - just let me know

**Comment by ShaunGrey** [comment]
copy/paste is better.

**Comment by nacu4** [comment]
C:\Users\ncunningham\Desktop\Ruby Files>ruby quickbasetest.rb
c-return C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:330 set_trace_func   Kernel
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:331 toggleTraceInfo QuickBase::Client
  c-call C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:331 block_given?   Kernel
c-return C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:331 block_given?   Kernel
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:342 toggleTraceInfo QuickBase::Client
  return C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:343 toggleTraceInfo QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:106 initialize QuickBase::Client
    call C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:191 setHTTPConnectionAndqbhost QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:192 setHTTPConnectionAndqbhost QuickBase::Client
    call C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:153 setHTTPConnection QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:154 setHTTPConnection QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:155 setHTTPConnection QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:156 setHTTPConnection QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:157 setHTTPConnection QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:165 setHTTPConnection QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:169 setHTTPConnection QuickBase::Client
  c-call C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:169       to_s FalseClass
c-return C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:169       to_s FalseClass
    call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:610        new Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:611        new Net::HTTP
  c-call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:611        new    Class
    call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:634 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:635 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:636 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:637 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:638 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:639 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:640 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:641 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:642 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:643 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:644 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:645 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:646 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:647 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:648 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:650 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:651 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:652 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:653 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:654 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:655 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:657 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:658 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:659 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:660 initialize Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:661 initialize Net::HTTP
  c-call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:661       each    Array
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 initialize Net::HTTP
  c-call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
c-return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 initialize Net::HTTP
  c-call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
c-return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 initialize Net::HTTP
  c-call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
c-return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 initialize Net::HTTP
  c-call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
c-return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 initialize Net::HTTP
  c-call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
c-return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 initialize Net::HTTP
  c-call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
c-return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 initialize Net::HTTP
  c-call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
c-return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 initialize Net::HTTP
  c-call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
c-return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 initialize Net::HTTP
  c-call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
c-return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 initialize Net::HTTP
  c-call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
c-return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 initialize Net::HTTP
  c-call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
c-return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:662 instance_variable_set   Kernel
c-return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:661       each    Array
  return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:664 initialize Net::HTTP
c-return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:611        new    Class
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:613        new Net::HTTP
    call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1017 proxy_class? Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1018 proxy_class? Net::HTTP
  return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1019 proxy_class? Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:619        new Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:620        new Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:628        new Net::HTTP
  return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:629        new Net::HTTP
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:171 setHTTPConnection QuickBase::Client
    call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:755   use_ssl= Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:756   use_ssl= Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:757   use_ssl= Net::HTTP
    call C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:738   started? Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:739   started? Net::HTTP
  return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:740   started? Net::HTTP
    line C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:760   use_ssl= Net::HTTP
  return C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:761   use_ssl= Net::HTTP
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:172 setHTTPConnection QuickBase::Client
  return C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:174 setHTTPConnection QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:193 setHTTPConnectionAndqbhost QuickBase::Client
    call C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:182  setqbhost QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:183  setqbhost QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:184  setqbhost QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:185  setqbhost QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:186  setqbhost QuickBase::Client
  c-call C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:186       to_s FalseClass
c-return C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:186       to_s FalseClass
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:187  setqbhost QuickBase::Client
  return C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:188  setqbhost QuickBase::Client
  return C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:194 setHTTPConnectionAndqbhost QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:107 initialize QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:108 initialize QuickBase::Client
    line C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:109 initialize QuickBase::Client
  return C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/quickbase_client-1.0.25/lib/QuickBaseClient.rb:121 initialize QuickBase::Client
c-return quickbasetest.rb:5         new    Class

**Comment by ShaunGrey** [comment]
Let's strip it real down. What do you get if you run this:

`require 'QuickBaseClient'`
`quickbase = QuickBase::Client.init ( {  "org" => "[token]",
                                        "usertoken" => "[usertoken]",
                                        "printRequestsAndResponses" => true} )`

**Comment by nacu4** [comment]
That worked! I even ran the "GetTableID" and that worked too, I got the output I needed. Thanks! Now I have to figure out how to run doQuery and printCSV's and things like that which I may open up, but starting out with the right connection is a great start. I'll close this issue. Thanks for your help!

**Comment by ShaunGrey** [comment]
anytime, dude. vote socialist

**Comment by garethlatwork** [comment]
Thanks ShaunGrey for helping to debug this.
