### ISSUE TITLE
downLoadFile function downloads an empty file

### ISSUE THREAD

**Issue by ShaunGrey** [garethlatwork/quickbase_client#7]
Hi! I asked this same question on the QuickBase community boards and they told me that this gem is "very old" and possibly not being maintained any more. I sure hope it's not true because it looks to me like the best one going!

Anywho, my issue is with the downLoadFile function. Using [this recipe](https://www.quickbase.com/db/bcdcajmrg?a=dr&r=3&rl=sy) as a guide, I created the following code for myself:

`contracts_dbid = "xxxxxxxxx"
qbc = QuickBase::Client.new(  "qbadmin@xxx.org", "XxXxXxX", nil, true, false, false, false, "xxx")
qbc.downLoadFile(contracts_dbid, "1352", "8")
File.open( "Test.pdf", "wb" ){|f|f.write(qbc.fileContents)}
`

However, when I run it, the file that it downloads ends up being exactly 0 bytes. Could I be doing something wrong?

**Comment by ShaunGrey** [comment]
I don't know if this would be considered the solution or just a workaround, but it appears that if I add "require 'httpclient'" to the top of my code, everything works perfectly.

**Comment by garethlatwork** [comment]
Sorry for not replying sooner.  That workaround should be fine.  I haven't worked on this gem for a while but I thought the quickbaseclient.rb was already requiring http_client.  BTW I don't think much has changed in the quickbase http API for several years, so this gem is probably still as useful as any other quickbase gems you might find.

**Comment by ShaunGrey** [comment]
Thanks!

I think this is by far the most useful QB gem I've come across. Thank you for making it!

**Comment by ShaunGrey** [comment]
Oh, and by the way, the gem does require httpclient, but it does so within a "begin-rescue-end" block. I don't really know enough about ruby to interpret that, but there you go.
